

module.exports = (sequelize,DataTypes) => {
    const Employee = sequelize.define('Employee',{
        userId:{
            type:DataTypes.INTEGER,
            allowNull:false,
            references:{
                model:'Users',
                key:'id'
            },
            onDelete:'CASCADE',
            onUpdate:'CASCADE'
        },
        staffNumber:{
            type:DataTypes.STRING,
            allowNull:true
        },
        position:{
            type:DataTypes.STRING,
            allowNull:true
        },
        managerId:{
            type:DataTypes.INTEGER,
            allowNull:true,
            references:{
                model:'Users',
                key:'id'
            },
            onDelete:'CASCADE',
            onUpdate:'CASCADE'
        },
        hireDate:{
            type:DataTypes.DATE,
            allowNull:false
        },
        statusId:{
            type:DataTypes.INTEGER,
            allowNull:false,
            references:{
                model:'Statuses',
                key:'id'
            },
            onDelete:'CASCADE',
            onUpdate:'CASCADE'
        },
        phone:{
            type:DataTypes.STRING,
            allowNull:true
        },
        emergencyContact:{
            type:DataTypes.STRING,
            allowNull:true
        },
        gender:{
            type:DataTypes.STRING,
            allowNull:true
        },
        dateOfBirth:{
            type:DataTypes.DATE,
            allowNull:true
        },
        nationalId:{
            type:DataTypes.STRING,
            allowNull:true
        },
        kraPin:{
            type:DataTypes.STRING,
            allowNull:true
        },
        employmentTypeId:{
            type:DataTypes.INTEGER,
            allowNull:false,
            references:{
                model:'EmploymentTypes',
                key:'id'
            },
            onDelete:'CASCADE',
            onUpdate:'CASCADE'
        },
        salary:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        workCounty:{
            type:DataTypes.STRING,
            allowNull:true
        },
        homeCounty:{
            type:DataTypes.STRING,
            allowNull:true
        },
        postalAddress:{
            type:DataTypes.STRING,
            allowNull:true
        },
        postalCode:{
            type:DataTypes.STRING,
            allowNull:true
        },
        stationName:{
            type:DataTypes.STRING,
            allowNull:true
        },
        skillLevel:{
            type:DataTypes.STRING,
            allowNull:true
        },
        company:{
            type:DataTypes.STRING,
            allowNull:true
        },
        children:{
            type:DataTypes.STRING,
            allowNull:true
        },
        avatarUrl:{
            type:DataTypes.STRING,
            allowNull:true
        },
        isActive:{
            type:DataTypes.BOOLEAN,
            defaultValue:true
        }
    },{
        timestamps:true,
        modelName:"Employees"
    });

    Employee.associate = (models) => {
        Employee.belongsTo(models.User,{foreignKey:"userId",as:"user"});
        Employee.belongsTo(models.User,{foreignKey:"managerId",as:"manager"});
        Employee.belongsTo(models.Status,{foreignKey:"statusId",as:"status"});
        Employee.belongsTo(models.EmploymentType,{foreignKey:"employmentTypeId",as:"employmentType"});
    }

    return Employee;

};